image: node:16.4.2

stages:
  - test
  - build

cache:
  paths:
    - node_modules/

validate:
  stage: test
  script:
    - npm install
    - npm run lint
    - npm run test-with-coverage

build_image:
  stage: build
  only:
    - /^release-.+$/
  script:
    - npm run build
    - npm config set registry https://gitlab.com/api/v4/projects/31753272/packages/npm/
    - npm config set -- '//gitlab.com/api/v4/projects/31753272/packages/npm/:_authToken' "$CI_JOB_TOKEN"
    - cd lib && npm publish
