image: node:16.4.2

stages:
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/

validate:
  stage: test
  script:
    - npm install
    - npm run lint
    - npm run test-with-coverage
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
  coverage: '/^(?:Statements|Branches|Functions|Lines)\s*:\s*([^%]+)/'

build_image:
  stage: build
  only:
    - /^release-.+$/
  script:
    - npm config set registry https://gitlab.com/api/v4/projects/31753272/packages/npm/
    - npm config set -- '//gitlab.com/api/v4/projects/31753272/packages/npm/:_authToken' "$CI_JOB_TOKEN"
    - npm run build
    - npm publish

pages:
  stage: deploy
  script:
    - npm run docs:external:build
    - npm run docs:internal:build
    - mkdir -p public/internal
    - mv docs/internal/* public/internal
  artifacts:
    paths:
      - public
  only:
    - main
    - develop
